<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Weak PasswordYour password must contain_754a4f</name>
   <tag></tag>
   <elementGuidId>6b3f3ec2-7884-4fdd-b135-526454d67849</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/form/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.oxd-grid-item.oxd-grid-item--gutters.user-password-cell</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>851a5d98-0dad-4975-bbee-5fd6f2ee8b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-grid-item oxd-grid-item--gutters user-password-cell</value>
      <webElementGuid>477c08d2-6153-42a3-9ba4-1849f6a7e17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Weak PasswordYour password must contain a lower-case letter, an upper-case letter, a digit and a special character. Try a different passwordFor a strong password, please use a hard to guess combination of text with upper and lower case characters, symbols and numbers</value>
      <webElementGuid>aa028b2e-8204-45be-bc87-92abef6f72ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-card-container&quot;]/form[@class=&quot;oxd-form&quot;]/div[@class=&quot;oxd-form-row user-password-row&quot;]/div[@class=&quot;oxd-grid-2 orangehrm-full-width-grid&quot;]/div[@class=&quot;oxd-grid-item oxd-grid-item--gutters user-password-cell&quot;]</value>
      <webElementGuid>1472f0c8-d19d-4326-a92d-3fdbe05baabc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/form/div[2]/div/div</value>
      <webElementGuid>4a9e03f0-221b-4346-af48-86666d869b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::div[4]</value>
      <webElementGuid>1d32c9a8-9fc0-4aa5-b882-f9f6bd397022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enabled'])[1]/following::div[8]</value>
      <webElementGuid>6f71bdc2-3fa4-4474-a3e6-2a938513e468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div</value>
      <webElementGuid>8afe0de8-2004-472b-9305-4b12ed67dc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Weak PasswordYour password must contain a lower-case letter, an upper-case letter, a digit and a special character. Try a different passwordFor a strong password, please use a hard to guess combination of text with upper and lower case characters, symbols and numbers' or . = 'Weak PasswordYour password must contain a lower-case letter, an upper-case letter, a digit and a special character. Try a different passwordFor a strong password, please use a hard to guess combination of text with upper and lower case characters, symbols and numbers')]</value>
      <webElementGuid>1d0ba4ed-48f8-4741-a650-eff8a0107019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
